### ISSUE TITLE
How can I enter K in knn for gpu? and what's the default value of k using gpu?

### ISSUE THREAD

**Issue by omarelnakib** [TDeVries/fast_knn_gpu#3]

**Comment by TDeVries** [comment]
Hi, the default K is 1, since it's using argmax (https://github.com/TDeVries/fast_knn_gpu/blob/b876326ffce04c6117f9cc63c5d67196f01a6008/fast_knn_tf.py#L55). To do top K I think you would just need to replace the argmax with top K (https://www.tensorflow.org/api_docs/python/tf/math/top_k).
