### ISSUE TITLE
where we build a model and fit the training dataset  in tensorflow knn?

### ISSUE THREAD

**Issue by NeveenHijazi** [TDeVries/fast_knn_gpu#5]
another question @TDeVries :
in sklearn KNN we build a model and train the data using : neigh.fit(X_train, Y_train)
then we make predication:  pred = neigh.predict(X_test)
but in tensoflow Knn where we build a model and fit the training dataset ???

**Comment by TDeVries** [comment]
KNN is a form of lazy learning, so there isn't really any model to be learned. When you run the KNN computation in TensorFlow it's equivalent to both neigh.fit and neigh.predict rolled into a single call.
